name: CI PIPELINE

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Check out code

      - name: Log in to Docker Hub
        run: echo "${{ secrets.Nguyenvan09 }}" | docker login -u "${{ secrets.thaovan01320 }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t cindy-jewelry/cindy-jewelry:latest .

      - name: Push Docker Image
        run: docker push cindy-jewelry/cindy-jewelry:latest
